spring.application.name=QuickTalk

# =========================================================
# SERVER
# =========================================================
server.port=${PORT:8080}
server.shutdown=graceful
server.forward-headers-strategy=framework
spring.lifecycle.timeout-per-shutdown-phase=10s

# =========================================================
# MONGODB
# =========================================================
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=quicktalk
spring.data.mongodb.auto-index-creation=true

# =========================================================
# ERROR SAFETY
# =========================================================
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-exception=false
